AZURE_TENANT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AZURE_CLIENT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AZURE_SUBSCRIPTION_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
AZURE_LOCATION: japaneast
AZURE_PRINCIPAL_ID: ''
AZURE_RESOURCE_GROUP_NAME: ''
DNS_ZONE_SUBSCRIPTION_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DNS_ZONE_RESOURCE_GROUP_NAME: rg-dns
DNS_ZONE_NAME: example.com
DNS_RECORD_NAME: nginxsite
DNS_WILDCARD: false
DNS_CERTIFICATE_EXISTS: false
LEGO_EMAIL: foo@example.com
LEGO_SERVER: https://acme-staging-v02.api.letsencrypt.org/directory
MS_TENANT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
MS_CLIENT_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
MS_ALLOWED_GROUP_ID: ''